Repository Centria-Hub/centria-hub, pull requests merged in 2025-03, with the labels that each got.

#39 Feat/payload
  Dockerfile
  app/(back)/admin/[[...segments]]/not-found.tsx
  app/(back)/admin/[[...segments]]/page.tsx
  app/(back)/admin/importMap.js
  app/(back)/api/[...slug]/route.ts
  app/(back)/api/graphql-playground/route.ts
  app/(back)/api/graphql/route.ts
  app/(back)/custom.scss
  app/(back)/layout.tsx
  app/(front)/(root)/about/page.tsx
  app/(front)/(root)/articles/[id]/page.tsx
  app/(front)/(root)/articles/page.tsx
  app/(front)/(root)/events/[id]/page.tsx
  app/(front)/(root)/events/page.tsx
  app/(front)/(root)/layout.tsx
  app/(front)/(root)/news/[id]/page.tsx
  app/(front)/(root)/news/page.tsx
  app/(front)/(root)/page.tsx
  app/(front)/data/articles.ts
  app/(front)/data/events.ts
  app/(front)/data/news.ts
  app/(front)/favicon.ico
  app/(front)/fonts/Nunito-Black.ttf
  app/(front)/fonts/Nunito-BlackItalic.ttf
  app/(front)/fonts/Nunito-Bold.ttf
  app/(front)/fonts/Nunito-BoldItalic.ttf
  app/(front)/fonts/Nunito-ExtraBold.ttf
  app/(front)/fonts/Nunito-ExtraBoldItalic.ttf
  app/(front)/fonts/Nunito-ExtraLight.ttf
  app/(front)/fonts/Nunito-ExtraLightItalic.ttf
  app/(front)/fonts/Nunito-Italic.ttf
  app/(front)/fonts/Nunito-Light.ttf
  app/(front)/fonts/Nunito-LightItalic.ttf
  app/(front)/fonts/Nunito-Medium.ttf
  app/(front)/fonts/Nunito-MediumItalic.ttf
  app/(front)/fonts/Nunito-Regular.ttf
  app/(front)/fonts/Nunito-SemiBold.ttf
  app/(front)/fonts/Nunito-SemiBoldItalic.ttf
  app/(front)/globals.css
  app/(front)/layout.tsx
  app/(root)/articles/[id]/page.tsx
  app/(root)/articles/page.tsx
  bun.lockb
  docker-compose.yml
  next.config.ts
  package.json
  payload-types.ts
  payload.config.ts
  tsconfig.json
  yarn.lock
Labels: enhancement

#40 fix: compose
  docker-compose.yml
Labels: bug

#41 fix: compose pg port
  docker-compose.yml
Labels: bug

#42 fix: add network to the compose
  docker-compose.yml
Labels: bug

#43 fix: add network to the compose
  docker-compose.yml
Labels: bug, enhancement

#44 fix: add pg url into the compose file
  docker-compose.yml
Labels: bug

#45 fix: add pg uri into the compose file
  docker-compose.yml
Labels: bug

#48 Feat/directus
  .dockerignore
  Dockerfile
  app/(back)/admin/[[...segments]]/not-found.tsx
  app/(back)/admin/[[...segments]]/page.tsx
  app/(back)/admin/importMap.js
  app/(back)/api/[...slug]/route.ts
  app/(back)/api/graphql-playground/route.ts
  app/(back)/api/graphql/route.ts
  app/(back)/custom.scss
  app/(back)/layout.tsx
  app/(root)/about/page.tsx
  app/(root)/articles/[id]/page.tsx
  app/(root)/articles/page.tsx
  app/(root)/events/[id]/page.tsx
  app/(root)/events/page.tsx
  app/(root)/layout.tsx
  app/(root)/news/[id]/page.tsx
  app/(root)/news/page.tsx
  app/(root)/page.tsx
  app/data/articles.ts
  app/data/events.ts
  app/data/news.ts
  app/favicon.ico
  app/fonts/Nunito-Black.ttf
  app/fonts/Nunito-BlackItalic.ttf
  app/fonts/Nunito-Bold.ttf
  app/fonts/Nunito-BoldItalic.ttf
  app/fonts/Nunito-ExtraBold.ttf
  app/fonts/Nunito-ExtraBoldItalic.ttf
  app/fonts/Nunito-ExtraLight.ttf
  app/fonts/Nunito-ExtraLightItalic.ttf
  app/fonts/Nunito-Italic.ttf
  app/fonts/Nunito-Light.ttf
  app/fonts/Nunito-LightItalic.ttf
  app/fonts/Nunito-Medium.ttf
  app/fonts/Nunito-MediumItalic.ttf
  app/fonts/Nunito-Regular.ttf
  app/fonts/Nunito-SemiBold.ttf
  app/fonts/Nunito-SemiBoldItalic.ttf
  app/globals.css
  app/layout.tsx
  docker-compose.yml
  migrations/20250307_100531.json
  migrations/20250307_100531.ts
  migrations/index.ts
  next.config.ts
  package.json
  payload-types.ts
  payload.config.ts
  scripts/depsCheck.js
  yarn.lock
Labels: enhancement

#49 fix: add public url
  docker-compose.yml
Labels: bug

#50 fix: add redirects to next config
  docker-compose.yml
  next.config.ts
Labels: enhancement

#51 fix: add backend url to compose
  docker-compose.yml
  next.config.ts
Labels: bug

#52 fix: add api endpoint to compose
  docker-compose.yml
Labels: bug

#53 fix: remove api endpoint to compose
  docker-compose.yml
Labels: bug

#54 Dev
  docker-compose.yml
Labels: enhancement

#55 chore: remove admin path from next config
  next.config.ts
Labels: config

#57 chore: add compose to gitignore
  .gitignore
  docker-compose.yml
Labels: config

#58 chore: add compose for local dev
  .gitignore
  docker-compose.yml
Labels: config

#59 feat: add test news api endpoint
  app/(root)/news/[id]/page.tsx
  app/(root)/news/page.tsx
  lib/directus.ts
  next.config.ts
  package.json
  yarn.lock
Labels: enhancement

#63 feat: add umami metrix
  app/layout.tsx
Labels: enhancement

#64 chore: enable CORS in docker-compose.yml
  docker-compose.yml
Labels: config

#65 chore: delete unused styles
  app/globals.css
Labels: task

#68 fix: fix the images fetch from the api
  app/(root)/news/[id]/page.tsx
  app/(root)/news/page.tsx
Labels: bug

#69 fix: fix the images quality
  app/(root)/news/[id]/page.tsx
  app/(root)/news/page.tsx
Labels: bug

#70 feat: integration api for article page
  app/(root)/articles/[id]/page.tsx
  app/(root)/articles/page.tsx
Labels: enhancement

#72 feat: integration api for events page
  app/(root)/events/[id]/page.tsx
  app/(root)/events/page.tsx
  components/AddToCalender.tsx
  components/OpenMapButton.tsx
Labels: enhancement
