Repository Centria-Hub/centria-hub, pull requests merged in 2025-02, with the labels that each got.

#16 fix: fix page name
  app/(root)/news/page.tsx
Labels: bug

#18 Fix/fix deploy issue
  .dockerignore
  Dockerfile
  next.config.ts
Labels: enhancement

#21 Update README.md
  README.md
Labels: documentation

#22 Update yarn.lock
  yarn.lock
Labels: bug

#25 feat: create event page ui
  app/(root)/events/[id]/page.tsx
  app/(root)/events/page.tsx
  app/data/events.ts
  components/DateFormat.tsx
Labels: enhancement

#26 fix: typo
  app/(root)/events/page.tsx
Labels: bug

#27 feat: create article page ui
  app/(root)/articles/[id]/page.tsx
  app/(root)/articles/page.tsx
  app/data/articles.ts
Labels: enhancement

#29 Chore/config
  .prettierrc.json
  .vscode/extensions.json
  .vscode/settings.json
  app/(root)/about/page.tsx
  app/(root)/events/[id]/page.tsx
  app/(root)/events/page.tsx
  app/(root)/layout.tsx
  app/(root)/news/[id]/page.tsx
  app/(root)/news/page.tsx
  app/(root)/page.tsx
  app/data/events.ts
  app/data/news.ts
  app/globals.css
  app/layout.tsx
  components/DateFormat.tsx
  components/Footer.tsx
  components/NavBar.tsx
  components/ui/badge.tsx
  components/ui/breadcrumb.tsx
  components/ui/button.tsx
  components/ui/card.tsx
  components/ui/carousel.tsx
  components/ui/checkbox.tsx
  components/ui/navigation-menu.tsx
  components/ui/pagination.tsx
  components/ui/select.tsx
  eslint.config.mjs
  lib/utils.ts
  next.config.ts
  package.json
  tailwind.config.ts
  yarn.lock
Labels: config

#32 feat: add back to top button
  app/(root)/layout.tsx
  bun.lockb
  components/BackToTop.tsx
  components/ui/tooltip.tsx
  package.json
  yarn.lock
Labels: enhancement

#31 feat: add active state to navbar
  components/NavBar.tsx
Labels: enhancement

#34 chore: add config
  .github/ISSUE_TEMPLATE/config.yml
Labels: documentation

#36 fix: sort/tags ui
  app/(root)/news/page.tsx
Labels: bug

#35 feat: add logo to navbar
  components/Footer.tsx
  components/NavBar.tsx
Labels: enhancement

#38 feat: add contact info to footer
  components/Footer.tsx
Labels: enhancement
